import { useEffect, useState } from "react";
import { Youtube, GraduationCap, CalendarDays, Award, Flag, FileText, Plus, Loader2 } from "lucide-react";
import { A } from "../adminColors";
import { loadAdminContent, addExploreContent } from "../../lib/adminBackend";

const GROUPS:any[]=[
 {key:"youtube",label:"YouTube Videos",Icon:Youtube},{key:"course",label:"Courses",Icon:GraduationCap},{key:"event",label:"Events",Icon:CalendarDays},{key:"scholarship",label:"Scholarships",Icon:Award},{key:"challenge",label:"Challenges",Icon:Flag},{key:"article",label:"Articles",Icon:FileText}
];
export function ExploreContentPage(){
 const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [open,setOpen]=useState(false); const [title,setTitle]=useState(""); const [category,setCategory]=useState("Coding"); const [type,setType]=useState("youtube"); const [metric,setMetric]=useState(""); const [url,setUrl]=useState("");
 const load=()=>{setLoading(true);loadAdminContent().then(setItems).catch(e=>setError(e.message||"Could not load content")).finally(()=>setLoading(false))}; useEffect(load,[]);
 const add=async()=>{if(!title.trim())return;try{await addExploreContent({title:title.trim(),category,content_type:type,metric_value:metric,url:url||undefined});setTitle("");setMetric("");setUrl("");setOpen(false);load()}catch(e:any){setError(e.message||"Could not add content")}};
 return <div style={{padding:"36px 40px 60px",maxWidth:1100,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",marginBottom:28}}><div><h1 style={{fontFamily:A.serif,fontSize:"1.5rem",color:A.text,margin:"0 0 6px"}}>Explore Content</h1><p style={{fontSize:".85rem",color:A.textMuted,margin:0}}>Content stored in Supabase.</p></div><button onClick={()=>setOpen(!open)} style={{border:0,borderRadius:10,padding:"10px 14px",background:A.gold,color:"white",fontWeight:700,display:"flex",gap:7,alignItems:"center",cursor:"pointer"}}><Plus size={15}/> Add content</button></div>
 {open&&<div style={{background:A.surface,border:`1px solid ${A.border}`,borderRadius:A.radius,padding:20,marginBottom:24,display:"grid",gridTemplateColumns:"2fr 1fr 1fr",gap:12}}><input placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)} style={{padding:10,border:`1px solid ${A.border}`,borderRadius:9}}/><select value={category} onChange={e=>setCategory(e.target.value)} style={{padding:10,border:`1px solid ${A.border}`,borderRadius:9}}><option>Coding</option><option>AI & ML</option><option>Communication</option><option>Mindset</option><option>UI/UX</option></select><select value={type} onChange={e=>setType(e.target.value)} style={{padding:10,border:`1px solid ${A.border}`,borderRadius:9}}>{GROUPS.map(g=><option key={g.key} value={g.key}>{g.label}</option>)}</select><input placeholder="Metric (e.g. 12.4k)" value={metric} onChange={e=>setMetric(e.target.value)} style={{padding:10,border:`1px solid ${A.border}`,borderRadius:9}}/><input placeholder="URL (optional)" value={url} onChange={e=>setUrl(e.target.value)} style={{padding:10,border:`1px solid ${A.border}`,borderRadius:9}}/><button onClick={add} style={{padding:10,border:0,borderRadius:9,background:A.gold,color:"white",fontWeight:700}}>Save</button></div>}
 {loading?<Loader2 size={20}/>:error?<div style={{color:A.red}}>{error}</div>:<div style={{display:"flex",flexDirection:"column",gap:26}}>{GROUPS.map(g=>{const rows=items.filter(x=>x.content_type===g.key);return <div key={g.key}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><g.Icon size={14} color={A.gold}/><span style={{fontSize:".78rem",fontWeight:700,textTransform:"uppercase",letterSpacing:".07em",color:A.textFaint}}>{g.label} ({rows.length})</span></div><div style={{background:A.surface,border:`1px solid ${A.border}`,borderRadius:A.radius,overflow:"hidden"}}>{rows.length?rows.map((x:any)=><div key={x.id} style={{display:"flex",alignItems:"center",gap:14,padding:"14px 20px",borderBottom:`1px solid ${A.borderMuted}`}}><span style={{flex:1,fontSize:".86rem",color:A.text}}>{x.title}</span><span style={{fontSize:".72rem",color:A.gold,background:A.goldLight,padding:"3px 10px",borderRadius:20}}>{x.category}</span><span style={{fontSize:".78rem",color:A.textFaint}}>{x.metric_value||"—"}</span></div>):<div style={{padding:18,fontSize:".8rem",color:A.textFaint}}>No content yet.</div>}</div></div>})}</div>}
 </div>;
}
