import { useEffect, useState } from "react";
import { Loader2, Users } from "lucide-react";
import { A } from "../adminColors";
import { loadAdminLearners } from "../../lib/adminBackend";
export function LearnersPage(){
 const [learners,setLearners]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{loadAdminLearners().then(setLearners).catch(e=>setError(e.message||"Could not load learners")).finally(()=>setLoading(false))},[]);
 return <div style={{padding:"36px 40px 60px",maxWidth:1180,margin:"0 auto"}}><div style={{marginBottom:24}}><h1 style={{fontFamily:A.serif,fontSize:"1.5rem",color:A.text,margin:"0 0 6px"}}>Learners</h1><p style={{fontSize:".85rem",color:A.textMuted,margin:0}}><Users size={14}/> {learners.length} profiles in Supabase.</p></div>{loading?<Loader2 size={20}/>:error?<div style={{color:A.red}}>{error}</div>:<div style={{background:A.surface,border:`1px solid ${A.border}`,borderRadius:A.radius,overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Name","Email","Role","Country","Career goal","Joined"].map(h=><th key={h} style={{textAlign:"left",padding:"14px 18px",fontSize:".7rem",color:A.textFaint,borderBottom:`1px solid ${A.border}`}}>{h}</th>)}</tr></thead><tbody>{learners.map((l,i)=><tr key={l.id} style={{borderBottom:i<learners.length-1?`1px solid ${A.borderMuted}`:"none"}}><td style={{padding:"13px 18px",fontWeight:600,color:A.text}}>{l.full_name||"Unnamed"}</td><td style={{padding:"13px 18px",color:A.textMuted}}>{l.email||"—"}</td><td style={{padding:"13px 18px",color:A.textMuted}}>{l.role||"student"}</td><td style={{padding:"13px 18px",color:A.textMuted}}>{l.country||"—"}</td><td style={{padding:"13px 18px",color:A.textMuted}}>{l.career_goal||"—"}</td><td style={{padding:"13px 18px",color:A.textFaint}}>{l.created_at?new Date(l.created_at).toLocaleDateString():"—"}</td></tr>)}</tbody></table></div>}</div>;
}
