import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { LayoutGrid, Users, Target, GraduationCap, CalendarClock, Compass, Sparkles, ShieldAlert, Settings as SettingsIcon, Search, Bell, Plus, Loader2 } from "lucide-react";
import { A } from "./adminColors";
import { StarfixNavMark } from "../components/StarfixLogoMark";
import { AdminOverview } from "./pages/AdminOverview";
import { LearnersPage } from "./pages/LearnersPage";
import { AdminPathsPage } from "./pages/AdminPathsPage";
import { AdminMentorsPage } from "./pages/AdminMentorsPage";
import { SessionsPage } from "./pages/SessionsPage";
import { ExploreContentPage } from "./pages/ExploreContentPage";
import { AIAssistantPage } from "./pages/AIAssistantPage";
import { ModerationPage } from "./pages/ModerationPage";
import { AdminSettingsPage } from "./pages/AdminSettingsPage";
import { isCurrentUserAdmin } from "../lib/adminBackend";
export type AdminPage = "overview"|"learners"|"paths"|"mentors"|"sessions"|"content"|"ai"|"moderation"|"settings";
const NAV:any[]=[{id:"overview",label:"Overview",Icon:LayoutGrid},{id:"learners",label:"Learners",Icon:Users},{id:"paths",label:"Growth Paths",Icon:Target},{id:"mentors",label:"Mentors",Icon:GraduationCap},{id:"sessions",label:"Sessions",Icon:CalendarClock},{id:"content",label:"Explore Content",Icon:Compass},{id:"ai",label:"AI Assistant",Icon:Sparkles},{id:"moderation",label:"Moderation",Icon:ShieldAlert},{id:"settings",label:"Settings",Icon:SettingsIcon}];
export function AdminLayout(){
 const[page,setPage]=useState<AdminPage>("overview");const[checking,setChecking]=useState(true);const[allowed,setAllowed]=useState(false);
 useEffect(()=>{isCurrentUserAdmin().then(setAllowed).finally(()=>setChecking(false))},[]);
 if(checking)return <div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:A.bg}}><Loader2 size={22}/></div>;
 if(!allowed)return <div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:A.bg,padding:24}}><div style={{background:A.surface,border:`1px solid ${A.border}`,borderRadius:18,padding:32,textAlign:"center",maxWidth:420}}><StarfixNavMark size={32}/><h1 style={{fontFamily:A.serif,color:A.text}}>Admin access required</h1><p style={{color:A.textMuted,fontSize:".86rem",lineHeight:1.6}}>Your signed-in Supabase profile does not have the admin role. Ask the Starfix owner to grant admin access.</p></div></div>;
 return <div style={{display:"flex",height:"100vh",background:A.bg,fontFamily:A.sans,overflow:"hidden"}}><aside style={{width:240,flexShrink:0,background:A.surface,borderRight:`1px solid ${A.border}`,display:"flex",flexDirection:"column",padding:"22px 14px"}}><div style={{display:"flex",alignItems:"center",gap:10,padding:"6px 10px 26px"}}><StarfixNavMark size={26}/><div><div style={{fontFamily:A.serif,fontSize:"1.05rem",fontWeight:700,color:A.text}}>Starfix</div><div style={{fontSize:".62rem",color:A.textFaint,letterSpacing:".08em",textTransform:"uppercase"}}>Admin</div></div></div><nav style={{display:"flex",flexDirection:"column",gap:2,flex:1}}>{NAV.map(item=>{const active=page===item.id;return <button key={item.id} onClick={()=>setPage(item.id)} style={{display:"flex",alignItems:"center",gap:11,padding:"10px 12px",borderRadius:A.radiusSm,border:0,cursor:"pointer",width:"100%",background:active?A.goldLight:"transparent",color:active?A.gold:A.textMuted,fontSize:".86rem",fontWeight:active?600:500,fontFamily:A.sans,textAlign:"left"}}><item.Icon size={16}/>{item.label}</button>})}</nav><div style={{padding:"12px 10px 4px",borderTop:`1px solid ${A.borderMuted}`,fontSize:".68rem",color:A.textFaint}}>Supabase Admin</div></aside><div style={{flex:1,display:"flex",flexDirection:"column",minWidth:0}}><header style={{height:64,flexShrink:0,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 28px",borderBottom:`1px solid ${A.border}`,background:A.bg}}><div style={{display:"flex",alignItems:"center",gap:9,background:A.surface,border:`1px solid ${A.border}`,borderRadius:12,padding:"9px 14px",width:340}}><Search size={15} color={A.textFaint}/><input placeholder="Search users, mentors, paths, resources" style={{border:0,outline:0,background:"transparent",fontSize:".82rem",color:A.text,width:"100%"}}/></div><div style={{display:"flex",alignItems:"center",gap:14}}><motion.button whileHover={{y:-2}} style={{position:"relative",width:36,height:36,borderRadius:"50%",border:`1px solid ${A.border}`,background:A.surface,display:"flex",alignItems:"center",justifyContent:"center"}}><Bell size={15} color={A.textMuted}/></motion.button><motion.button whileHover={{y:-2}} style={{width:36,height:36,borderRadius:"50%",border:0,background:A.gold,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}><Plus size={16}/></motion.button></div></header><main style={{flex:1,overflow:"auto"}}>{page==="overview"&&<AdminOverview onNavigate={setPage}/>} {page==="learners"&&<LearnersPage/>} {page==="paths"&&<AdminPathsPage/>} {page==="mentors"&&<AdminMentorsPage/>} {page==="sessions"&&<SessionsPage/>} {page==="content"&&<ExploreContentPage/>} {page==="ai"&&<AIAssistantPage/>} {page==="moderation"&&<ModerationPage/>} {page==="settings"&&<AdminSettingsPage/>}</main></div></div>;
}
